version: "3.7"
services:
  frontend:
    container_name: frontend
    build: 
        context: ./frontend
        dockerfile: Dockerfile.prod
    ports:
      - 80:80
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    environment: 
      - API_BASE_URL=http://localhost
      - API_PORT=8080
    depends_on:
      - backend

  backend:
    container_name: backend
    build: 
        context: ./backend
        dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
      
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - "27017:27017"
networks:
  react-express:
  express-mongo:
