FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci

COPY . .

EXPOSE 8080

CMD [ "npm", "run", "dev" ]
