import { IRecord } from './record';

export interface IPlayer extends IRecord {
    First_Name: string;
    Last_Name: string;
    
    College: string | number;
    Height: number;
    Weight: number;
}

export interface IDraftPlayer extends IPlayer {
    Agility: number;
    Dash: number;
    Position_Group: string;
    Grade: number;
    Jump: number;
    Position_Specific: number;
    Solecismic: number;
    Strength: number;
    Developed: number;
	Interviewed: number;

    High_Accuracy: number;
	High_Adjust_to_Ball: number;
	High_Avoid_Drops: number;
	High_Big_Play_Receiving: number;
	High_Blitz_Pickup: number;
	High_Blocking_Strength: number;
	"High_Bump-and-Run_Defense": number;
	High_Courage: number;
	High_Deep_Passes: number;
	High_Directional_Punting: number;
	High_Elusiveness: number;
	High_Endurance: number;
	High_Get_Downfield: number;
	High_Hang_Time: number;
	High_Hole_Recognition: number;
	High_Intercepting: number;
	High_Kick_Holding: number;
	High_Kick_Returns: number;
	High_Kicking_Accuracy: number;
	High_Kicking_Power: number;
	High_Kickoff_Distance: number;
	High_Kickoff_Hang_Time: number;
	High_Long_Passes: number;
	High_Long_Snapping: number;
	"High_Man-to-Man_Defense": number;
	High_Medium_Passes: number;
	High_Pass_Blocking: number;
	High_Pass_Rush_Strength: number;
	High_Pass_Rush_Technique: number;
	High_Play_Diagnosis: number;
	High_Power_Inside: number;
	High_Punishing_Hitter: number;
	High_Punt_Returns: number;
	High_Punting_Power: number;
	High_Read_Defense: number;
	High_Route_Running: number;
	High_Run_Blocking: number;
	High_Run_Defense: number;
	High_Run_Frequency: number;
	High_Screen_Passes: number;
	High_Sense_Rush: number;
	High_Short_Passes: number;
	High_Special_Teams: number;
	High_Speed: number;
	High_Speed_Outside: number;
	"High_Third-Down_Receiving": number;
	"High_Third-Down_Runs": number;
	High_Third_Down: number;
	High_Timing: number;
	"High_Two-Minute_Offense": number;
	High_Zone_Defense: number;
	Low_Accuracy: number;
	Low_Adjust_to_Ball: number;
	Low_Avoid_Drops: number;
	Low_Big_Play_Receiving: number;
	Low_Blitz_Pickup: number;
	Low_Blocking_Strength: number;
	"Low_Bump-and-Run_Defense": number;
	Low_Courage: number;
	Low_Deep_Passes: number;
	Low_Directional_Punting: number;
	Low_Elusiveness: number;
	Low_Endurance: number;
	Low_Get_Downfield: number;
	Low_Hang_Time: number;
	Low_Hole_Recognition: number;
	Low_Intercepting: number;
	Low_Kick_Holding: number;
	Low_Kick_Returns: number;
	Low_Kicking_Accuracy: number;
	Low_Kicking_Power: number;
	Low_Kickoff_Distance: number;
	Low_Kickoff_Hang_Time: number;
	Low_Long_Passes: number;
	Low_Long_Snapping: number;
	"Low_Man-to-Man_Defense": number;
	Low_Medium_Passes: number;
	Low_Pass_Blocking: number;
	Low_Pass_Rush_Strength: number;
	Low_Pass_Rush_Technique: number;
	Low_Play_Diagnosis: number;
	Low_Power_Inside: number;
	Low_Punishing_Hitter: number;
	Low_Punt_Returns: number;
	Low_Punting_Power: number;
	Low_Read_Defense: number;
	Low_Route_Running: number;
	Low_Run_Blocking: number;
	Low_Run_Defense: number;
	Low_Run_Frequency: number;
	Low_Screen_Passes: number;
	Low_Sense_Rush: number;
	Low_Short_Passes: number;
	Low_Special_Teams: number;
	Low_Speed: number;
	Low_Speed_Outside: number;
	"Low_Third-Down_Receiving": number;
	"Low_Third-Down_Runs": number;
	Low_Third_Down: number;
	Low_Timing: number;
	"Low_Two-Minute_Offense": number;
	Low_Zone_Defense: number;
}

export interface IPlayerInformation extends IPlayer {
    Position: string;
}